### ISSUE TITLE
Serialization of fit result/parameters causes segmentation fault after program finished.

### ISSUE THREAD

**Issue by zhang-jingqing** [ComPWA/ComPWA#173] opened 2019-04-12 13:54 UTC
When I use serialization method to save fit result, although the fit result can be successfully
saved and loaded, when the program finishes all its tasks and returns from main function,
there will be segmentation fault. I only found it related with the serialization of  ParameterList 
class. I don't know the detailed reason.

It doesn't damage our result, but just looks not so good. It's better to fix it later.

To Reproduce,
put the SerializationTest.cpp and CMakeLists.txt to a sub-directory of ComPWA,
e.g., ComPWA/Examples/SerializationTest and compile it with the ComPWA framework.
run it by $build/Examples/SerializationTest/Serialization then you may see such result:

[pc1 SerializationTest]$ ./SerializationTest 
2019-04-12 15:43:07,134 INFO [default] hello
Segmentation fault

Note: 

when compile it, if links it wilth only Core,
you can safely use:
#include <boost/archive/xml_iarchive.hpp>                                        
#include <boost/archive/xml_oarchive.hpp>                                        
BOOST_CLASS_EXPORT(ComPWA::ParameterList)                                        
BOOST_CLASS_EXPORT(ComPWA::FitParameter)                                         
BOOST_CLASS_EXPORT(ComPWA::FitResult)

and there will be NO segmentation.

but if compile it with Minuit2IF also,
any BOOST_CLASSZ_EXPORT statement 
combined with any of the two includes:
#include <boost/archive/xml_iarchive.hpp>                                        
#include <boost/archive/xml_oarchive.hpp> 
will cause segmentation fault, after program execution finished.

[SerializationTest.tar.gz](https://github.com/ComPWA/ComPWA/files/3073551/SerializationTest.tar.gz)

**Comment by spflueger** [comment] 2019-04-12 13:56
Ok thanks @zhang-jingqing. I will take a look at it next week

**Comment by spflueger** [comment] 2019-04-15 08:31
Hi @zhang-jingqing,
I cannot reproduce this. Can you post the error log? Do you build ComPWA in Debug or Release mode? And which compiler and boost version do you use?

**Comment by spflueger** [comment] 2019-04-15 13:08
It seems to be a bug in boost/serialization (https://github.com/boostorg/serialization/pull/105). Affected versions should be boost 1.65 to 1.68.

**Comment by spflueger** [comment] 2019-05-03 15:20
I close this issue for now. In case the problem persists with higher boost versions, feel free to reopen this issue

**Closed by spflueger** 2019-05-03 15:20 UTC
Labels: Priority: Medium, Status: Blocked, Status: Review Needed, Type: Bug
